const JS_SUFFIXES = {
	"Node JS": "Node.js",
	"React JS": "React.js",
	"Vue JS": "Vue.js",
	"Express JS": "Express.js",
	"D3 JS": "D3.js",
	"Next JS": "Next.js",
	"JQuery": "JQuery.js",
	"Web3 JS": "Web3.js",
	"Ethers JS": "Ethers.js",
	"Bitcoin JS": "Bitcoin.js",
	"Ethereum JS": "Ethereum.js",
	"Truffle JS": "Truffle.js",
	"Chainlink JS": "Chainlink.js",
	"IPFS JS": "IPFS.js",
	"Moralis JS": "Moralis.js",
	"Solidity JS": "Solidity.js",
}
